### ISSUE TITLE
Action corrupts local rust registry

### ISSUE THREAD

**Issue by ChristopherRabotin** [model-checking/kani-github-action#30]
I tried to run my typical Github action for Kani. Historically, this has never caused any issues for the installation of crates. However, on my recent pushes, cargo seems to no longer be able to find optional registries: https://github.com/nyx-space/hifitime/actions/runs/4399579815/jobs/7704213779 . I am not sure what has happened.

**Comment by karkhaz** [comment]
Hi there,

I'm not a rust expert but this [comment](https://github.com/rust-lang/cargo/issues/9069#issuecomment-1408773982) suggests that sparse registries are used from Rust 1.68 (released last week 2023-03-09). Continuing to look into this

**Comment by adpaco-aws** [comment]
Hi @ChristopherRabotin , it doesn't look like [Hifitime uses the Kani Github Action](https://github.com/nyx-space/hifitime/blob/master/.github/workflows/formal_verification.yml).

In any case, the step that installs the stable Rust toolchain is setting `CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse` (resetting that variable may work as a patch for now). It seems that it's always failing to compile `der` using sparse registries, right?

**Comment by ChristopherRabotin** [comment]
Using the Github Action does not cause the issue: https://github.com/nyx-space/hifitime/actions/runs/4417201736/jobs/7742569934 . Closing, and sorry for opening it before checking that I was indeed using the action.

**Comment by adpaco-aws** [comment]
No worries! I'm glad to see the Kani GitHub Action being useful 😄
